# Generated by Django 4.2.9 on 2024-03-02 01:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Casal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_casamento', models.DateField()),
                ('status_casal_ecc', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], max_length=7)),
                ('status_matrimonio', models.CharField(choices=[('casado', 'Casado'), ('divorciado', 'Divorciado')], max_length=10)),
                ('data_cadastro_casal', models.DateTimeField(auto_now_add=True)),
                ('data_ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('quantidade_eventos_participados', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=11, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=20)),
                ('cidade', models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(3)])),
                ('bairro', models.CharField(max_length=60, validators=[django.core.validators.MinLengthValidator(3)])),
                ('rua', models.CharField(max_length=70, validators=[django.core.validators.MinLengthValidator(2)])),
                ('cep', models.CharField(max_length=9, validators=[django.core.validators.MinLengthValidator(8)])),
                ('numero_residencial', models.CharField(max_length=6, validators=[django.core.validators.MinLengthValidator(1)])),
                ('referencia', models.CharField(max_length=30)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EquipeDirigente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], max_length=7)),
                ('senha', models.CharField(max_length=512)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EquipeEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('quantidade_membros', models.IntegerField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('equipe_criadora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecc_admin.equipedirigente')),
            ],
        ),
        migrations.CreateModel(
            name='MembroIgreja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('primeiro_nome', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2)])),
                ('segundo_nome', models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(2)])),
                ('nascimento', models.DateField()),
                ('sexo', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino')], max_length=1)),
                ('data_registro', models.DateTimeField(auto_now=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('contato', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecc_admin.contato')),
                ('endereco', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecc_admin.endereco')),
            ],
        ),
        migrations.CreateModel(
            name='Habilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('equipe_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecc_admin.equipeevento')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('equipe_criadora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecc_admin.equipedirigente')),
            ],
        ),
        migrations.AddField(
            model_name='equipeevento',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecc_admin.evento'),
        ),
        migrations.AddField(
            model_name='equipedirigente',
            name='cpf_esposa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esposa_dirigente', to='ecc_admin.membroigreja'),
        ),
        migrations.AddField(
            model_name='equipedirigente',
            name='cpf_marido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marido_dirigente', to='ecc_admin.membroigreja'),
        ),
        migrations.CreateModel(
            name='EdicaoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, null=True)),
                ('equipe_dirigente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecc_admin.equipedirigente')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecc_admin.evento')),
            ],
        ),
        migrations.CreateModel(
            name='ConviteEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aceito', 'Aceito'), ('recusado', 'Recusado')], max_length=8)),
                ('justificativa', models.CharField(max_length=100, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('casal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecc_admin.casal')),
                ('equipe_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecc_admin.equipeevento')),
            ],
        ),
        migrations.CreateModel(
            name='CasalHabilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecc_admin.casal')),
                ('habilidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecc_admin.habilidade')),
            ],
        ),
        migrations.CreateModel(
            name='CasalEdicaoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecc_admin.casal')),
                ('edicao_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecc_admin.edicaoevento')),
                ('equipe_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecc_admin.equipeevento')),
            ],
        ),
        migrations.AddField(
            model_name='casal',
            name='cpf_esposa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esposa', to='ecc_admin.membroigreja'),
        ),
        migrations.AddField(
            model_name='casal',
            name='cpf_marido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marido', to='ecc_admin.membroigreja'),
        ),
    ]
